baseURL       = "https://stupendous-sfogliatella-92085b.netlify.app"
languageCode  = "en-us"
theme         = "roxo-hugo"
summarylength = 25

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages]
  [languages.th]
    contentDir = 'content/th'
    disabled = false
    languageCode = 'th-TH'
    languageName = 'Thai'
    title = 'โอเพ่นดรีม'
    weight = 2
        # Site Menus
    [languages.th.menu]
      # Navbar Menus
      [[languages.th.menu.nav]]
        name    = "หน้าหลัก"
        url     = "th"
        weight  = 1
      [[languages.th.menu.nav]]
        name    = "เกี่ยวกับรา"
        url     = "th/about"
        weight  = 2
      [[languages.th.menu.nav]]
        name    = "Projects"
        url     = "th/portfolio"
        weight  = 3
      [[languages.th.menu.nav]]
        name    = "Blog"
        url     = "th/blog"
        weight  = 4
      [[languages.th.menu.nav]]
        name    = "Contact Us"
        url     = "th/contact"
        weight  = 5

  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageName = 'English'
    title = 'Opendream'
    weight = 1
    # Site Menus
    [languages.en.menu]
      # Navbar Menus
      [[languages.en.menu.nav]]
        name    = "Home"
        url     = "en"
        weight  = 1
      [[languages.en.menu.nav]]
        name    = "About"
        url     = "en/about"
        weight  = 2
      [[languages.en.menu.nav]]
        name    = "Projects"
        url     = "en/portfolio"
        weight  = 3
      [[languages.en.menu.nav]]
        name    = "Blog"
        url     = "en/blog"
        weight  = 4
      [[languages.en.menu.nav]]
        name    = "Contact Us"
        url     = "en/contact"
        weight  = 5


    # # Site Menus
    # [menu]
    #   # Navbar Menus
    #   [[menu.nav]]
    #     name    = "Home"
    #     url     = ""
    #     weight  = 1
    #   [[menu.nav]]
    #     name    = "About"
    #     url     = "about"
    #     weight  = 2
    #   [[menu.nav]]
    #     name    = "Projects"
    #     url     = "portfolio"
    #     weight  = 3
    #   [[menu.nav]]
    #     name    = "Blog"
    #     url     = "blog"
    #     weight  = 4
    #   [[menu.nav]]
    #     name    = "Contact Us"
    #     url     = "contact"
    #     weight  = 5


# Site Params
[params]
  logo = "images/od_logo.svg"
  logo_footer = "images/od_logo_white.svg"
  favicon_icon = "images/favicon.ico"
  favicon_shortcut_icon = "images/favicon.png"
  custom_stylesheets = []   # [ "scss/my_1.scss", "scss/my_2.scss" ]
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/USAg2Jl"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/opendream-about.jpg"
    heading               = "Sustainable Social Impact with Technology"
    tagline               = "WE CREATE"
    primary_button        = "View Projects"
    primary_button_url    = "portfolio"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"

  [params.blog]
    read_more             = "read more"

  [params.portfolio]
    enable    = true
    title     = "OUR RECENT WORKS"
    subtitle  = "Crafting experiences and seeking to make the complex clear & beautiful."
    view_project = "view project"
    more_works = "MORE WORKS"
    scroll_down = "scroll down"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S DEVELOP TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    params.footer.qr_print = false
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "Opendream Co., Ltd. (Head Office)<br />349 SJ Infinite One Business Complex,<br />10th Unit 1004-1005 Vibhavadi-Rangsit Road,<br />Chompol Chatuchak Bangkok 10900, Thailand"
      phone   = "Phone: +66.90.559.8288"
      email   = "Email: info [a] opendream.co.th"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Company"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Projects"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Medium"
          url  = "#"
        [[params.footer.social.link]]
          name = "Behance"
          url  = "#"
        [[params.footer.social.link]]
          name = "Dribbble"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "We create:"
        description = "Sustainable Social Impact<br />with Technology"
      [params.footer.back_to_top]
        description = "I want to <br> visit again"
